package con.tbs.payload;

public enum LogActivityActions {
    USER_REGISTRATION_SUCCESSFUL,
    USER_REGISTRATION_FAILED,
    AUTHENTICATION_SUCCESSFUL,
    AUTHENTICATION_FAILED,
    CASH_IN_SUCCESSFUL,
    CASH_IN_FAILED,
    CASH_OUT_SUCCESSFUL,
    CASH_OUT_FAILED,
    TRANSFER_SUCCESSFUL,
    TRANSFER_FAILED,
    GET_SUCCESS,
    GET_FAILED
}
